export const icons = {
    "class<org\\.telegram\\.desktop>": "",
    "class<kitty>": "",
    "class<kitty> title<.*top.*>": "",
    "class<kitty> title<.*pacman.*>": "",
    "class<com\\.github\\.weclaw1\\.ImageRoll|nomacs>": "",
    "title<(.*[$%#] *)?nvim.*>": "",
    "title<(.*[$%#] *)?([hb]|nv)top.*>": "",
    "class<firefox>": "",
    "class<discord>": "",
    "title<Discord.*>": "",
    "title<.[0-9]+. Discord.*>": " °",
    "title<Signal>": "󰍡",
    "title<(.* - )?(.[0-9]+. )?YouTube.*>": "",
    "title<.* - Gmail .*>": "󰊫",
    "class<obsidian>": "󱞁",
    "class<ONLYOFFICE Desktop Editors>": "󰈙",
    "class<calibre-.*>": "",
    "class<org\\.qbittorrent\\.qBittorrent>": "",
    "class<org\\.kde\\.kdeconnect.*>": "",
    "class<mpv>": "",
    "class<vlc>": "󰕼",
    "class<Gimp-.*>": "",
    "class<steam.*>": "󰓓",
    "class<steam> title<Friends List>": "",
    "class<steam_app_[0-9]+>": "󰮂",
    "title<Winetricks.*>": "󰡶",
    "class<lutris>": "🦦",
    "class<Spotify>": "",
    "class<jetbrains-idea(-ce)?>": "",
    "title<.*youtube.*>": "",
    "class<Code>": "󰨞",
    "class<com\\.obsproject\\.Studio|zoom>": "",
    "class<io\\.github\\.whoozle\\.android-file-transfer>": "",
    "class<(Chromium)|(Chrome)>": "",
    "class<(slack|Slack)>": "󰒱",
    "class<.*rgb.*>": ""
};
